apiVersion: v2
name: release-flow-test
description: Release Flow Test - Simple HTTP server for testing release workflows
type: application
version: 0.0.8
appVersion: "0.0.8"
home: https://github.com/ChrisJBurns/release-flow-test
sources:
  - https://github.com/ChrisJBurns/release-flow-test
maintainers:
  - name: Chris Burns
    url: https://github.com/ChrisJBurns
keywords:
  - test
  - release-flow
annotations:
  org.opencontainers.image.source: "https://github.com/ChrisJBurns/release-flow-test"
  org.opencontainers.image.licenses: "Apache-2.0"
